### ISSUE TITLE
怎么执行不起来呢

### ISSUE THREAD

**Issue by wjb12** [xinyu198736/js2image#5]
执行命令是js2image？执行后报错
D:\Documents\GitHub\js2image-master>js2image

C:\Users\Administrator\AppData\Roaming\npm\node_modules\js2image\bin\cli:9
var out = argv.o || source.replace(".js",".xmas.js");
                           ^
TypeError: Cannot call method 'replace' of undefined
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\js2image\bin\cli:9:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by small-tou** [comment]
看文档额，需要加参数

**Comment by small-tou** [comment]
至少要有 -s 参数指定处理的js代码路径
